export const LIST_PRIZES_REQUEST = "LIST_PRIZES_REQUEST";
export const LIST_PRIZES_SUCCESS = "LIST_PRIZES_SUCCESS";
export const LIST_PRIZES_FAIL = "LIST_PRIZES_FAIL";
export const LIST_PRIZES_RESET = "LIST_PRIZES_RESET";
